/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Anomalies */
        get: operations["list_anomalies_api_v1_anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        /** Ingest Event */
        post: operations["ingest_event_api_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Batch */
        post: operations["ingest_batch_api_v1_events_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incident Summary */
        get: operations["incident_summary_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["audit_api_v1_incidents__incident_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_api_v1_incidents__incident_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explanation */
        get: operations["explanation_api_v1_incidents__incident_id__explanation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/hypotheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hypotheses */
        get: operations["hypotheses_api_v1_incidents__incident_id__hypotheses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/investigation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investigation */
        get: operations["investigation_api_v1_incidents__incident_id__investigation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendations */
        get: operations["recommendations_api_v1_incidents__incident_id__recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute */
        post: operations["recompute_api_v1_incidents__incident_id__recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_v1_incidents__incident_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeline */
        get: operations["timeline_api_v1_incidents__incident_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quarantine */
        get: operations["list_quarantine_api_v1_quarantine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulator/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset
         * @description Execute the full demo reset sequence (blueprint §5.2, P1-22).
         *
         *     Stops the simulator, clears demo rows, reloads topology,
         *     re-seeds history, resets the simulator clock, and writes DEMO_RESET audit.
         */
        post: operations["reset_api_v1_simulator_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulator/scenarios/{scenario_id}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger */
        post: operations["trigger_api_v1_simulator_scenarios__scenario_id__trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulator/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_v1_simulator_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulator/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_simulator_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulator/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop */
        post: operations["stop_api_v1_simulator_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topology */
        get: operations["topology_api_v1_topology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topology/blast-radius/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blast Radius */
        get: operations["blast_radius_api_v1_topology_blast_radius__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topology/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Path */
        get: operations["path_api_v1_topology_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisRun */
        AnalysisRun: {
            /** Algorithm Version */
            algorithm_version: string;
            /** Analysis Run Id */
            analysis_run_id: string;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Incident Id */
            incident_id: string;
            /** Input Fingerprint */
            input_fingerprint: string;
            /** Revision */
            revision: number;
            status: components["schemas"]["AnalysisRunStatus"];
            /** Trigger Event Id */
            trigger_event_id: string | null;
        };
        /**
         * AnalysisRunStatus
         * @enum {string}
         */
        AnalysisRunStatus: "building" | "current" | "superseded" | "failed";
        /** AnomalyListResponse */
        AnomalyListResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Items */
            items: components["schemas"]["OverviewAnomaly"][];
        };
        /**
         * AuditActorType
         * @enum {string}
         */
        AuditActorType: "system" | "user" | "llm";
        /** AuditRecord */
        AuditRecord: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: string | null;
            actor_type: components["schemas"]["AuditActorType"];
            /** Analysis Run Id */
            analysis_run_id: string | null;
            /** Audit Id */
            audit_id: string;
            /** Object Id */
            object_id: string;
            /** Object Type */
            object_type: string;
            /** Payload */
            payload: Record<string, never>;
            /** Request Id */
            request_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** BatchIngestionResponse */
        BatchIngestionResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Request Id */
            request_id: string;
            /** Results */
            results: components["schemas"]["IngestionMutationResponse"][];
        };
        /** CanonicalEvent */
        CanonicalEvent: {
            /** Entity Id */
            entity_id: string;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            modality: components["schemas"]["Modality"];
            /** Quality Flags */
            quality_flags?: string[];
            /** Raw Payload */
            raw_payload?: Record<string, never>;
            /** Schema Version */
            schema_version: string;
            /** Severity */
            severity: number;
            /** Signal Name */
            signal_name?: string | null;
            /** Signal Value */
            signal_value?: number | null;
            /** Source */
            source: string;
            /** Source Record Id */
            source_record_id?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Trace Or Session Id */
            trace_or_session_id?: string | null;
            /** Unit */
            unit?: string | null;
        };
        /** EvidenceCoverage */
        EvidenceCoverage: {
            /** Available */
            available: number;
            /** Expected */
            expected: number;
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Analysis Run Id */
            analysis_run_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence Id */
            evidence_id: string;
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Incident Id */
            incident_id: string;
            kind: components["schemas"]["EvidenceKind"];
            /** Reason Code */
            reason_code: string;
            /** Relevance */
            relevance: number;
            /** Source Event Id */
            source_event_id: string | null;
            /** Statement */
            statement: string;
        };
        /**
         * EvidenceKind
         * @enum {string}
         */
        EvidenceKind: "observed" | "correlated" | "conflicting" | "missing";
        /** ExplanationClaim */
        ExplanationClaim: {
            /** Claim */
            claim: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** ExplanationOutput */
        ExplanationOutput: {
            /** Analysis Run Id */
            analysis_run_id: string;
            /** Claims */
            claims: components["schemas"]["ExplanationClaim"][];
            /** Diagnostic Step Ids */
            diagnostic_step_ids: string[];
            /**
             * Generator
             * @enum {string}
             */
            generator: "template" | "llm";
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Incident Id */
            incident_id: string;
            /** Remediation Step Ids */
            remediation_step_ids: string[];
            /** Summary */
            summary: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Hypothesis */
        Hypothesis: {
            /** Analysis Run Id */
            analysis_run_id: string;
            /** Candidate Entity Id */
            candidate_entity_id: string;
            evidence_coverage: components["schemas"]["EvidenceCoverage"];
            /** Evidence Score */
            evidence_score: number;
            /** Factor Scores */
            factor_scores: {
                [key: string]: number;
            };
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Hypothesis Type */
            hypothesis_type: string;
            /** Incident Id */
            incident_id: string;
            /** Rank */
            rank: number;
            /** Summary */
            summary: string;
        };
        /**
         * IncidentStatus
         * @enum {string}
         */
        IncidentStatus: "open" | "investigating" | "resolved" | "rejected";
        /** IncidentSummary */
        IncidentSummary: {
            /** Affected Entity Ids */
            affected_entity_ids: string[];
            /** Anomaly Count */
            anomaly_count: number;
            /** Confirmed Hypothesis Id */
            confirmed_hypothesis_id: string | null;
            /** Current Analysis Run Id */
            current_analysis_run_id: string | null;
            /** Incident Id */
            incident_id: string;
            /**
             * Last Event At
             * Format: date-time
             */
            last_event_at: string;
            /** Primary Entity Id */
            primary_entity_id: string;
            /** Severity */
            severity: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["IncidentStatus"];
            /** Title */
            title: string;
            /** Top Hypothesis Id */
            top_hypothesis_id: string | null;
        };
        /** IngestionMutationResponse */
        IngestionMutationResponse: {
            /**
             * Analysis State
             * @default not_started
             * @enum {string}
             */
            analysis_state: "not_started" | "processed";
            /** Collapsed Group Id */
            collapsed_group_id?: string | null;
            /** Event Id */
            event_id?: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Incident Id */
            incident_id?: string | null;
            /** Quarantine Id */
            quarantine_id?: string | null;
            /** Reason Codes */
            reason_codes?: string[];
            /** Representative Event Id */
            representative_event_id?: string | null;
            /** Request Id */
            request_id: string;
            /** Source Record Id */
            source_record_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "collapsed" | "quarantined";
        };
        /** InvestigationResponse */
        InvestigationResponse: {
            analysis_run: components["schemas"]["AnalysisRun"];
            /** Analysis Run Id */
            analysis_run_id: string;
            /** Evidence By Hypothesis */
            evidence_by_hypothesis: {
                [key: string]: components["schemas"]["EvidenceItem"][];
            };
            explanation: components["schemas"]["ExplanationOutput"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Hypotheses */
            hypotheses: components["schemas"]["Hypothesis"][];
            incident: components["schemas"]["IncidentSummary"];
            /** Recommendations By Hypothesis */
            recommendations_by_hypothesis: {
                [key: string]: components["schemas"]["PlaybookRecommendation"][];
            };
            /** Reviews */
            reviews: components["schemas"]["ReviewRecord"][];
            /** Timeline */
            timeline: components["schemas"]["TimelineItem"][];
            topology: components["schemas"]["TopologySnapshot"];
        };
        /**
         * Modality
         * @enum {string}
         */
        Modality: "metric" | "log" | "alert" | "config_change";
        /** OverviewAnomaly */
        OverviewAnomaly: {
            /** Anomaly Id */
            anomaly_id: string;
            /** Anomaly Type */
            anomaly_type: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Detector Id */
            detector_id: string;
            /** Entity Id */
            entity_id: string;
            /** Score */
            score: number;
        };
        /** PlaybookRecommendation */
        PlaybookRecommendation: {
            /** Analysis Run Id */
            analysis_run_id: string;
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Incident Id */
            incident_id: string;
            /** Instructions */
            instructions: string;
            /** Rationale */
            rationale: string;
            /** Recommendation Id */
            recommendation_id: string;
            /** Requires Human Approval */
            requires_human_approval: boolean;
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "low" | "medium" | "high";
            /** Step Id */
            step_id: string;
            /**
             * Step Type
             * @enum {string}
             */
            step_type: "diagnostic" | "remediation";
            /** Title */
            title: string;
        };
        /**
         * RawIngestionRequest
         * @description One source-specific record plus its source-adapter identity.
         */
        RawIngestionRequest: {
            /** Raw */
            raw: Record<string, never>;
            /** Request Id */
            request_id?: string | null;
            /** Source */
            source: string;
        };
        /**
         * ReviewDecision
         * @enum {string}
         */
        ReviewDecision: "confirmed" | "rejected" | "evidence_requested";
        /**
         * ReviewMutationResponse
         * @description Idempotent mutation envelope required by blueprint §18.4.
         */
        ReviewMutationResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Request Id */
            request_id: string;
            review: components["schemas"]["ReviewRecord"];
        };
        /** ReviewRecord */
        ReviewRecord: {
            /** Analysis Run Id */
            analysis_run_id: string;
            /** Client Action Id */
            client_action_id: string;
            /** Comment */
            comment: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            decision: components["schemas"]["ReviewDecision"];
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Incident Id */
            incident_id: string;
            /** Requested Evidence Id */
            requested_evidence_id: string | null;
            /** Review Id */
            review_id: string;
            /** Reviewer */
            reviewer: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** Analysis Run Id */
            analysis_run_id: string;
            /** Client Action Id */
            client_action_id: string;
            /**
             * Comment
             * @default
             */
            comment: string;
            decision: components["schemas"]["ReviewDecision"];
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Requested Evidence Id */
            requested_evidence_id?: string | null;
            /** Reviewer */
            reviewer: string;
        };
        /** SimulatorResetResponse */
        SimulatorResetResponse: {
            /** Baseline Ticks Emitted */
            baseline_ticks_emitted: number;
            /** Baseline Ticks Required */
            baseline_ticks_required: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Metric Interval Seconds */
            metric_interval_seconds: number;
            /** Reset Audit Id */
            reset_audit_id: string;
            /** Scenario Id */
            scenario_id: string | null;
            /** Scenario State */
            scenario_state: string;
            /** Seed */
            seed: number;
            /** Source Health */
            source_health: components["schemas"]["SourceHealth"][];
            /** Sources */
            sources: {
                [key: string]: components["schemas"]["SourceCounters"];
            };
            /**
             * State
             * @enum {string}
             */
            state: "stopped" | "running" | "paused" | "ready" | "triggering" | "completed";
            /**
             * Virtual Clock
             * Format: date-time
             */
            virtual_clock: string;
        };
        /** SimulatorStatusResponse */
        SimulatorStatusResponse: {
            /** Baseline Ticks Emitted */
            baseline_ticks_emitted: number;
            /** Baseline Ticks Required */
            baseline_ticks_required: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Metric Interval Seconds */
            metric_interval_seconds: number;
            /** Scenario Id */
            scenario_id: string | null;
            /** Scenario State */
            scenario_state: string;
            /** Seed */
            seed: number;
            /** Source Health */
            source_health: components["schemas"]["SourceHealth"][];
            /** Sources */
            sources: {
                [key: string]: components["schemas"]["SourceCounters"];
            };
            /**
             * State
             * @enum {string}
             */
            state: "stopped" | "running" | "paused" | "ready" | "triggering" | "completed";
            /**
             * Virtual Clock
             * Format: date-time
             */
            virtual_clock: string;
        };
        /** SourceCounters */
        SourceCounters: {
            /** Accepted */
            accepted: number;
            /** Collapsed */
            collapsed: number;
            /** Emitted */
            emitted: number;
            /** Quarantined */
            quarantined: number;
        };
        /** SourceHealth */
        SourceHealth: {
            /** Accepted */
            accepted: number;
            /** Collapsed */
            collapsed: number;
            /** Fixture Version */
            fixture_version?: string | null;
            /** Last Ingest At */
            last_ingest_at: string | null;
            /** Quarantined */
            quarantined: number;
            /** Source Id */
            source_id: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "metrics" | "logs" | "alerts" | "config_changes" | "topology";
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "error";
        };
        /** TimelineItem */
        TimelineItem: {
            /**
             * Attachment Decision
             * @enum {string}
             */
            attachment_decision: "attached" | "excluded";
            /** Attachment Reasons */
            attachment_reasons: string[];
            /** Attachment Score */
            attachment_score: number;
            event: components["schemas"]["CanonicalEvent"];
            /** Hypothesis Relevance */
            hypothesis_relevance?: {
                [key: string]: string[];
            };
        };
        /** TopologyEdge */
        TopologyEdge: {
            relation_type: components["schemas"]["TopologyRelation"];
            /** Relationship */
            relationship: string;
            /** Source */
            source: string;
            /** State */
            state?: ("impact_path" | "blast_radius") | null;
            /** Target */
            target: string;
        };
        /** TopologyNode */
        TopologyNode: {
            /** Criticality */
            criticality: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Service */
            service: string;
            /** State */
            state?: ("suspected_root" | "primary_affected" | "impact_path" | "blast_radius") | null;
            /** Type */
            type: string;
        };
        /**
         * TopologyRelation
         * @enum {string}
         */
        TopologyRelation: "depends_on" | "sends_traffic_to";
        /** TopologySnapshot */
        TopologySnapshot: {
            /** Edges */
            edges: components["schemas"]["TopologyEdge"][];
            /** Fixture Version */
            fixture_version: string;
            /** Nodes */
            nodes: components["schemas"]["TopologyNode"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_anomalies_api_v1_anomalies_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                limit?: number;
                modality?: string | null;
                entity_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_event_api_v1_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RawIngestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_batch_api_v1_events_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RawIngestionRequest"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchIngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["IncidentStatus"] | null;
                primary_entity_id?: string | null;
                min_severity?: number | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    incident_summary_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_v1_incidents__incident_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_api_v1_incidents__incident_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["EvidenceItem"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explanation_api_v1_incidents__incident_id__explanation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hypotheses_api_v1_incidents__incident_id__hypotheses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hypothesis"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigation_api_v1_incidents__incident_id__investigation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendations_api_v1_incidents__incident_id__recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["PlaybookRecommendation"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_api_v1_incidents__incident_id__recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_v1_incidents__incident_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_v1_incidents__incident_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quarantine_api_v1_quarantine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    reset_api_v1_simulator_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorResetResponse"];
                };
            };
        };
    };
    trigger_api_v1_simulator_scenarios__scenario_id__trigger_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_v1_simulator_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorStatusResponse"];
                };
            };
        };
    };
    status_api_v1_simulator_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorStatusResponse"];
                };
            };
        };
    };
    stop_api_v1_simulator_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorStatusResponse"];
                };
            };
        };
    };
    topology_api_v1_topology_get: {
        parameters: {
            query?: {
                incident_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologySnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    blast_radius_api_v1_topology_blast_radius__entity_id__get: {
        parameters: {
            query: {
                mode: "dependency" | "traffic";
                max_hops?: number;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    path_api_v1_topology_path_get: {
        parameters: {
            query: {
                source: string;
                target: string;
                relation_type: components["schemas"]["TopologyRelation"];
                direction: "forward" | "reverse";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
