"""initial_contract_schema

Revision ID: 2eff20be3718
Revises:
Create Date: 2026-07-14 19:34:14.979316
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2eff20be3718'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trigger_event_id', sa.String(), nullable=True),
    sa.Column('input_fingerprint', sa.String(), nullable=False),
    sa.Column('algorithm_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'revision', name='uq_analysis_incident_revision')
    )
    op.create_index('ix_analysis_incident_fingerprint', 'analysis_runs', ['incident_id', 'input_fingerprint'], unique=False)
    op.create_index('ix_analysis_incident_status', 'analysis_runs', ['incident_id', 'status'], unique=False)
    op.create_index('uq_analysis_current_per_incident', 'analysis_runs', ['incident_id'], unique=True, sqlite_where=sa.text("status = 'current'"))
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_object', 'audit_logs', ['object_type', 'object_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('criticality', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_service'), 'entities', ['service'], unique=False)
    op.create_table('historical_incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('confirmed_cause', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('feature_vector', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_incidents_fingerprint'), 'historical_incidents', ['fingerprint'], unique=True)
    op.create_table('hypotheses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_run_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('candidate_entity_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('factor_scores', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.CheckConstraint('evidence_score >= 0 AND evidence_score <= 100', name='ck_hypothesis_score'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['candidate_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'rank', name='uq_hypothesis_run_rank')
    )
    op.create_index(op.f('ix_hypotheses_type'), 'hypotheses', ['type'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('primary_entity_id', sa.String(), nullable=False),
    sa.Column('affected_entity_ids', sa.JSON(), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('current_analysis_run_id', sa.String(), nullable=True),
    sa.Column('top_hypothesis_id', sa.String(), nullable=True),
    sa.Column('confirmed_hypothesis_id', sa.String(), nullable=True),
    sa.CheckConstraint('severity >= 0 AND severity <= 1', name='ck_incidents_severity'),
    sa.ForeignKeyConstraint(['confirmed_hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['current_analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['primary_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['top_hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_primary_entity_id'), 'incidents', ['primary_entity_id'], unique=False)
    op.create_index(op.f('ix_incidents_started_at'), 'incidents', ['started_at'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('quarantined_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarantined_events_received_at'), 'quarantined_events', ['received_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('signal_name', sa.String(), nullable=True),
    sa.Column('signal_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('trace_or_session_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_record_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint('severity >= 0 AND severity <= 1', name='ck_events_severity'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_record_id', name='uq_events_source_record')
    )
    op.create_index('ix_events_entity_timestamp', 'events', ['entity_id', 'timestamp'], unique=False)
    op.create_index('ix_events_modality_timestamp', 'events', ['modality', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_trace_or_session_id'), 'events', ['trace_or_session_id'], unique=False)
    op.create_table('explanations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_run_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('generator', sa.String(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanations_analysis_run_id'), 'explanations', ['analysis_run_id'], unique=False)
    op.create_index('ix_explanations_incident_created', 'explanations', ['incident_id', 'created_at'], unique=False)
    op.create_table('playbook_recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_run_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbook_recommendations_hypothesis_id'), 'playbook_recommendations', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_playbook_recommendations_incident_id'), 'playbook_recommendations', ['incident_id'], unique=False)
    op.create_table('topology_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_to', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('source_entity_id <> target_entity_id', name='ck_topology_no_self_edge'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_id', 'target_entity_id', 'relation_type', name='uq_topology_typed_edge')
    )
    op.create_index('ix_topology_source_relation', 'topology_edges', ['source_entity_id', 'relation_type'], unique=False)
    op.create_index('ix_topology_target_relation', 'topology_edges', ['target_entity_id', 'relation_type'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('detector_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('context_only', sa.Boolean(), nullable=False),
    sa.Column('can_open_incident', sa.Boolean(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 1', name='ck_anomalies_score'),
    sa.CheckConstraint('threshold >= 0 AND threshold <= 1', name='ck_anomalies_threshold'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_event_id'), 'anomalies', ['event_id'], unique=False)
    op.create_index(op.f('ix_anomalies_score'), 'anomalies', ['score'], unique=False)
    op.create_index(op.f('ix_anomalies_window_end'), 'anomalies', ['window_end'], unique=False)
    op.create_table('collapsed_event_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('representative_event_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['representative_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collapsed_event_groups_fingerprint'), 'collapsed_event_groups', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_collapsed_event_groups_last_seen'), 'collapsed_event_groups', ['last_seen'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_run_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(kind = 'missing' AND source_event_id IS NULL) OR (kind <> 'missing' AND source_event_id IS NOT NULL)", name='ck_evidence_missing_source'),
    sa.CheckConstraint('relevance >= 0 AND relevance <= 1', name='ck_evidence_relevance'),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_hypothesis_kind', 'evidence', ['hypothesis_id', 'kind'], unique=False)
    op.create_table('incident_event_evaluations',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('attachment_score', sa.Float(), nullable=False),
    sa.Column('attachment_reasons', sa.JSON(), nullable=False),
    sa.CheckConstraint("decision IN ('attached','excluded')", name='ck_event_eval_decision'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'event_id')
    )
    op.create_table('incident_events',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('attachment_score', sa.Float(), nullable=False),
    sa.Column('attachment_reasons', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'event_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('analysis_run_id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('client_action_id', sa.String(), nullable=False),
    sa.Column('requested_evidence_id', sa.String(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['requested_evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'client_action_id', name='uq_review_client_action')
    )
    op.create_index('ix_reviews_incident_created', 'reviews', ['incident_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_incident_created', table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('incident_events')
    op.drop_table('incident_event_evaluations')
    op.drop_index('ix_evidence_hypothesis_kind', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_collapsed_event_groups_last_seen'), table_name='collapsed_event_groups')
    op.drop_index(op.f('ix_collapsed_event_groups_fingerprint'), table_name='collapsed_event_groups')
    op.drop_table('collapsed_event_groups')
    op.drop_index(op.f('ix_anomalies_window_end'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_score'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_event_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index('ix_topology_target_relation', table_name='topology_edges')
    op.drop_index('ix_topology_source_relation', table_name='topology_edges')
    op.drop_table('topology_edges')
    op.drop_index(op.f('ix_playbook_recommendations_incident_id'), table_name='playbook_recommendations')
    op.drop_index(op.f('ix_playbook_recommendations_hypothesis_id'), table_name='playbook_recommendations')
    op.drop_table('playbook_recommendations')
    op.drop_index('ix_explanations_incident_created', table_name='explanations')
    op.drop_index(op.f('ix_explanations_analysis_run_id'), table_name='explanations')
    op.drop_table('explanations')
    op.drop_index(op.f('ix_events_trace_or_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index('ix_events_modality_timestamp', table_name='events')
    op.drop_index('ix_events_entity_timestamp', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_quarantined_events_received_at'), table_name='quarantined_events')
    op.drop_table('quarantined_events')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_started_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_primary_entity_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_hypotheses_type'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_historical_incidents_fingerprint'), table_name='historical_incidents')
    op.drop_table('historical_incidents')
    op.drop_index(op.f('ix_entities_service'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_audit_object', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_analysis_current_per_incident', table_name='analysis_runs', sqlite_where=sa.text("status = 'current'"))
    op.drop_index('ix_analysis_incident_status', table_name='analysis_runs')
    op.drop_index('ix_analysis_incident_fingerprint', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
